"""init

Revision ID: d2ffda8754b9
Revises: 
Create Date: 2026-04-27 17:22:01.437030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ffda8754b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricas_id'), 'metricas', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('latitud', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('longitud', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taller_id'), 'taller', ['id'], unique=False)
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculo_id'), 'vehiculo', ['id'], unique=False)
    op.create_table('emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('latitud', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('longitud', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('tipo', sa.Enum('bateria', 'llanta', 'choque', 'motor', 'otro', name='tipo_enum'), nullable=True),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', name='prioridad_enum'), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_proceso', 'atendido', 'cancelado', name='estado_enum'), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergencia_id'), 'emergencia', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_table('tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tecnico_id'), 'tecnico', ['id'], unique=False)
    op.create_table('analisis_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergencia_id', sa.Integer(), nullable=True),
    sa.Column('transcripcion', sa.Text(), nullable=True),
    sa.Column('clasificacion', sa.String(length=50), nullable=True),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['emergencia_id'], ['emergencia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analisis_ia_id'), 'analisis_ia', ['id'], unique=False)
    op.create_table('asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergencia_id', sa.Integer(), nullable=True),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('asignado', 'aceptado', 'rechazado', name='estado_asignacion_enum'), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['emergencia_id'], ['emergencia.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnico.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_id'), 'asignaciones', ['id'], unique=False)
    op.create_table('evidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergencia_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('imagen', 'audio', 'texto', name='tipo_evidencia_enum'), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['emergencia_id'], ['emergencia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencia_id'), 'evidencia', ['id'], unique=False)
    op.create_table('historial_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergencia_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_proceso', 'atendido', 'cancelado', name='estado_historial_enum'), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['emergencia_id'], ['emergencia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_id'), 'historial_estados', ['id'], unique=False)
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergencia_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('metodo', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'pagado', 'fallido', name='estado_pago_enum'), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['emergencia_id'], ['emergencia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pago_id'), 'pago', ['id'], unique=False)
    op.create_table('ubicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergencia_id', sa.Integer(), nullable=True),
    sa.Column('latitud', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('longitud', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['emergencia_id'], ['emergencia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ubicaciones_id'), 'ubicaciones', ['id'], unique=False)
    op.create_table('comisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=True),
    sa.Column('porcentaje', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comisiones_id'), 'comisiones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comisiones_id'), table_name='comisiones')
    op.drop_table('comisiones')
    op.drop_index(op.f('ix_ubicaciones_id'), table_name='ubicaciones')
    op.drop_table('ubicaciones')
    op.drop_index(op.f('ix_pago_id'), table_name='pago')
    op.drop_table('pago')
    op.drop_index(op.f('ix_historial_estados_id'), table_name='historial_estados')
    op.drop_table('historial_estados')
    op.drop_index(op.f('ix_evidencia_id'), table_name='evidencia')
    op.drop_table('evidencia')
    op.drop_index(op.f('ix_asignaciones_id'), table_name='asignaciones')
    op.drop_table('asignaciones')
    op.drop_index(op.f('ix_analisis_ia_id'), table_name='analisis_ia')
    op.drop_table('analisis_ia')
    op.drop_index(op.f('ix_tecnico_id'), table_name='tecnico')
    op.drop_table('tecnico')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_emergencia_id'), table_name='emergencia')
    op.drop_table('emergencia')
    op.drop_index(op.f('ix_vehiculo_id'), table_name='vehiculo')
    op.drop_table('vehiculo')
    op.drop_index(op.f('ix_taller_id'), table_name='taller')
    op.drop_table('taller')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_metricas_id'), table_name='metricas')
    op.drop_table('metricas')
    # ### end Alembic commands ###
